Added french
webcompat/testcase-reducer pull request #15
Opened 2019-06-25 07:23 UTC by magsout

maybe @karlcow could take a look?

i'm not really sure about `refine`

2019-06-26 02:39 UTC, wisniewskit requested changes
This works for me, thanks (assuming karlcow is fine with the strings). But I'm afraid that I just added one more string for a general error to the list:
```
  "errorNoResultsAvailable": {
    "message": "No reduced results could be obtained."
  },
```

Sorry for the churn!

2019-06-26 16:03 UTC, magsout commented
@wisniewskit done

2019-06-28 01:07 UTC, karlcow requested changes
@magsout @wisniewskit Some suggestions

2019-06-28 01:07 UTC, karlcow commented on _locales/fr/messages.json
> +    "message": "Impossible d'acceder au noeud... cross-origin iframe?"
```suggestion
    "message": "Impossible d'accéder au nœud… cross-origin iframe?"
```

2019-06-28 01:07 UTC, karlcow commented on _locales/fr/messages.json
> +    "message": "Extrait le code HTML et CSS pour générer des cas de test. "
```suggestion
    "message": "Extrait le code HTML et CSS pour générer un test."
```

2019-06-28 01:07 UTC, karlcow commented on _locales/fr/messages.json
> +    "message": "Inclure les noeuds parents"
```suggestion
    "message": "Inclure les nœuds parent"
```

2019-06-28 01:07 UTC, karlcow commented on _locales/fr/messages.json
> +    "message": "Inclure les meta tags important"
```suggestion
    "message": "Inclure les meta tags importants"
```

2019-06-28 01:07 UTC, karlcow commented on _locales/fr/messages.json
> +    "message": "Perdre vos modification et restreindre à nouveau ?"
```suggestion
    "message": "Perdre vos modifications initiales et réduire à nouveau ?"
```

2019-06-28 01:07 UTC, karlcow commented on _locales/fr/messages.json
> +    "message": "Testcase Reducer a trouvé une règle CSS inattendue :"
```suggestion
    "message": "Testcase Reducer a trouvé une règle CSS inattendue : "
```

2019-06-28 01:07 UTC, karlcow commented on _locales/fr/messages.json
> +    "message": "Afficher l'iframe dans sa taille original "
```suggestion
    "message": "Afficher l'iframe dans sa taille originale"
```

2019-06-28 01:07 UTC, karlcow commented on _locales/fr/messages.json
> +    "message": "Restreindre"
```suggestion
    "message": "Réduire"
```

2019-06-28 06:48 UTC, magsout commented
@karlcow oups sorry the misreading.
fixed and committed, thanks for your review.

r @wisniewskit ?

2019-07-02 15:09 UTC, wisniewskit commented
Works for me, thanks! Just FYI, I'll try to ping you whenever I'm going to roll another release, and there are new strings to localize.

2019-07-02 15:09 UTC, merged